/*
 * Copyright(C) (2023) Sapper Inc. (open.source at zyient dot io)
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.07.29 at 09:55:26 AM IST 
//


package io.zyient.intake.model;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the https.genpact_com.pvai package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: https.genpact_com.pvai
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link SourceDocSet }
     * 
     */
    public SourceDocSet createSourceDocSet() {
        return new SourceDocSet();
    }

    /**
     * Create an instance of {@link SourceDocSet.Products }
     * 
     */
    public SourceDocSet.Products createSourceDocSetProducts() {
        return new SourceDocSet.Products();
    }

    /**
     * Create an instance of {@link SourceDocSet.AdditionalCaseDetails }
     * 
     */
    public SourceDocSet.AdditionalCaseDetails createSourceDocSetAdditionalCaseDetails() {
        return new SourceDocSet.AdditionalCaseDetails();
    }

    /**
     * Create an instance of {@link SourceDocSet.AdverseEvents }
     * 
     */
    public SourceDocSet.AdverseEvents createSourceDocSetAdverseEvents() {
        return new SourceDocSet.AdverseEvents();
    }

    /**
     * Create an instance of {@link SourceDocSet.SourceDocuments }
     * 
     */
    public SourceDocSet.SourceDocuments createSourceDocSetSourceDocuments() {
        return new SourceDocSet.SourceDocuments();
    }

    /**
     * Create an instance of {@link SourceDocSet.Transaction }
     * 
     */
    public SourceDocSet.Transaction createSourceDocSetTransaction() {
        return new SourceDocSet.Transaction();
    }

    /**
     * Create an instance of {@link SourceDocSet.Seriousness }
     * 
     */
    public SourceDocSet.Seriousness createSourceDocSetSeriousness() {
        return new SourceDocSet.Seriousness();
    }

    /**
     * Create an instance of {@link SourceDocSet.Products.Product }
     * 
     */
    public SourceDocSet.Products.Product createSourceDocSetProductsProduct() {
        return new SourceDocSet.Products.Product();
    }

    /**
     * Create an instance of {@link SourceDocSet.AdditionalCaseDetails.AdditionalCaseDetail }
     * 
     */
    public SourceDocSet.AdditionalCaseDetails.AdditionalCaseDetail createSourceDocSetAdditionalCaseDetailsAdditionalCaseDetail() {
        return new SourceDocSet.AdditionalCaseDetails.AdditionalCaseDetail();
    }

    /**
     * Create an instance of {@link SourceDocSet.AdverseEvents.AdverseEvent }
     * 
     */
    public SourceDocSet.AdverseEvents.AdverseEvent createSourceDocSetAdverseEventsAdverseEvent() {
        return new SourceDocSet.AdverseEvents.AdverseEvent();
    }

    /**
     * Create an instance of {@link SourceDocSet.SourceDocuments.SourceDocument }
     * 
     */
    public SourceDocSet.SourceDocuments.SourceDocument createSourceDocSetSourceDocumentsSourceDocument() {
        return new SourceDocSet.SourceDocuments.SourceDocument();
    }

}
