/*
 * Copyright(C) (2023) Sapper Inc. (open.source at zyient dot io)
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.07.29 at 09:55:26 AM IST 
//


package io.zyient.intake.model;

import javax.xml.bind.annotation.*;
import javax.xml.datatype.XMLGregorianCalendar;
import java.math.BigInteger;
import java.util.ArrayList;
import java.util.List;


/**
 * <p>Java class for anonymous complex type.
 *
 * <p>The following schema fragment specifies the expected content contained within this class.
 *
 * <pre>
 * &lt;complexType&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="transaction" minOccurs="0"&gt;
 *           &lt;complexType&gt;
 *             &lt;complexContent&gt;
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                 &lt;sequence&gt;
 *                   &lt;element name="transaction_number" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *                   &lt;element name="transaction_date" type="{http://www.w3.org/2001/XMLSchema}dateTime" minOccurs="0"/&gt;
 *                 &lt;/sequence&gt;
 *               &lt;/restriction&gt;
 *             &lt;/complexContent&gt;
 *           &lt;/complexType&gt;
 *         &lt;/element&gt;
 *         &lt;element name="source_documents"&gt;
 *           &lt;complexType&gt;
 *             &lt;complexContent&gt;
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                 &lt;sequence&gt;
 *                   &lt;element name="source_document" maxOccurs="unbounded"&gt;
 *                     &lt;complexType&gt;
 *                       &lt;complexContent&gt;
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                           &lt;sequence&gt;
 *                             &lt;element name="document_name"&gt;
 *                               &lt;simpleType&gt;
 *                                 &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *                                   &lt;minLength value="1"/&gt;
 *                                 &lt;/restriction&gt;
 *                               &lt;/simpleType&gt;
 *                             &lt;/element&gt;
 *                             &lt;element name="edms_doc_object_id"&gt;
 *                               &lt;simpleType&gt;
 *                                 &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *                                   &lt;minLength value="1"/&gt;
 *                                 &lt;/restriction&gt;
 *                               &lt;/simpleType&gt;
 *                             &lt;/element&gt;
 *                             &lt;element name="process_document" type="{http://www.w3.org/2001/XMLSchema}boolean"/&gt;
 *                             &lt;element name="document_language"&gt;
 *                               &lt;simpleType&gt;
 *                                 &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *                                   &lt;minLength value="2"/&gt;
 *                                   &lt;maxLength value="2"/&gt;
 *                                 &lt;/restriction&gt;
 *                               &lt;/simpleType&gt;
 *                             &lt;/element&gt;
 *                             &lt;element name="document_uri" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *                           &lt;/sequence&gt;
 *                         &lt;/restriction&gt;
 *                       &lt;/complexContent&gt;
 *                     &lt;/complexType&gt;
 *                   &lt;/element&gt;
 *                 &lt;/sequence&gt;
 *               &lt;/restriction&gt;
 *             &lt;/complexContent&gt;
 *           &lt;/complexType&gt;
 *         &lt;/element&gt;
 *         &lt;element name="source_system" minOccurs="0"&gt;
 *           &lt;simpleType&gt;
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *               &lt;minLength value="1"/&gt;
 *             &lt;/restriction&gt;
 *           &lt;/simpleType&gt;
 *         &lt;/element&gt;
 *         &lt;element name="received_from_license_partner" minOccurs="0"&gt;
 *           &lt;simpleType&gt;
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *               &lt;enumeration value="Yes"/&gt;
 *               &lt;enumeration value="No"/&gt;
 *             &lt;/restriction&gt;
 *           &lt;/simpleType&gt;
 *         &lt;/element&gt;
 *         &lt;element name="private_data" minOccurs="0"&gt;
 *           &lt;simpleType&gt;
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *               &lt;enumeration value="Yes"/&gt;
 *               &lt;enumeration value="No"/&gt;
 *             &lt;/restriction&gt;
 *           &lt;/simpleType&gt;
 *         &lt;/element&gt;
 *         &lt;element name="case_type" minOccurs="0"&gt;
 *           &lt;simpleType&gt;
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *               &lt;minLength value="2"/&gt;
 *               &lt;maxLength value="2"/&gt;
 *             &lt;/restriction&gt;
 *           &lt;/simpleType&gt;
 *         &lt;/element&gt;
 *         &lt;element name="country_of_occurrence" minOccurs="0"&gt;
 *           &lt;simpleType&gt;
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *               &lt;minLength value="2"/&gt;
 *               &lt;maxLength value="2"/&gt;
 *             &lt;/restriction&gt;
 *           &lt;/simpleType&gt;
 *         &lt;/element&gt;
 *         &lt;element name="adverse_events" minOccurs="0"&gt;
 *           &lt;complexType&gt;
 *             &lt;complexContent&gt;
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                 &lt;sequence&gt;
 *                   &lt;element name="adverse_event" maxOccurs="unbounded"&gt;
 *                     &lt;complexType&gt;
 *                       &lt;complexContent&gt;
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                           &lt;sequence&gt;
 *                             &lt;element name="event_verbatim" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *                             &lt;element name="event_code" type="{http://www.w3.org/2001/XMLSchema}nonNegativeInteger" minOccurs="0"/&gt;
 *                             &lt;element name="event_code_type" minOccurs="0"&gt;
 *                               &lt;simpleType&gt;
 *                                 &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *                                   &lt;enumeration value="PT"/&gt;
 *                                   &lt;enumeration value="LLT"/&gt;
 *                                 &lt;/restriction&gt;
 *                               &lt;/simpleType&gt;
 *                             &lt;/element&gt;
 *                           &lt;/sequence&gt;
 *                         &lt;/restriction&gt;
 *                       &lt;/complexContent&gt;
 *                     &lt;/complexType&gt;
 *                   &lt;/element&gt;
 *                 &lt;/sequence&gt;
 *               &lt;/restriction&gt;
 *             &lt;/complexContent&gt;
 *           &lt;/complexType&gt;
 *         &lt;/element&gt;
 *         &lt;element name="additional_case_details" minOccurs="0"&gt;
 *           &lt;complexType&gt;
 *             &lt;complexContent&gt;
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                 &lt;sequence&gt;
 *                   &lt;element name="additional_case_detail" maxOccurs="unbounded"&gt;
 *                     &lt;complexType&gt;
 *                       &lt;complexContent&gt;
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                           &lt;sequence&gt;
 *                             &lt;element name="additional_data_description" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *                             &lt;element name="additional_data_value" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *                           &lt;/sequence&gt;
 *                         &lt;/restriction&gt;
 *                       &lt;/complexContent&gt;
 *                     &lt;/complexType&gt;
 *                   &lt;/element&gt;
 *                 &lt;/sequence&gt;
 *               &lt;/restriction&gt;
 *             &lt;/complexContent&gt;
 *           &lt;/complexType&gt;
 *         &lt;/element&gt;
 *         &lt;element name="products" minOccurs="0"&gt;
 *           &lt;complexType&gt;
 *             &lt;complexContent&gt;
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                 &lt;sequence&gt;
 *                   &lt;element name="product" maxOccurs="unbounded"&gt;
 *                     &lt;complexType&gt;
 *                       &lt;complexContent&gt;
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                           &lt;sequence&gt;
 *                             &lt;element name="product_name" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *                             &lt;element name="generic_name" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *                           &lt;/sequence&gt;
 *                         &lt;/restriction&gt;
 *                       &lt;/complexContent&gt;
 *                     &lt;/complexType&gt;
 *                   &lt;/element&gt;
 *                 &lt;/sequence&gt;
 *               &lt;/restriction&gt;
 *             &lt;/complexContent&gt;
 *           &lt;/complexType&gt;
 *         &lt;/element&gt;
 *         &lt;element name="receive_date" type="{http://www.w3.org/2001/XMLSchema}date" minOccurs="0"/&gt;
 *         &lt;element name="priority" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="reporter_type" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="receiving_site" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="study_id" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="serious_unexpected_reaction" minOccurs="0"&gt;
 *           &lt;simpleType&gt;
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *               &lt;enumeration value="Yes"/&gt;
 *               &lt;enumeration value="No"/&gt;
 *             &lt;/restriction&gt;
 *           &lt;/simpleType&gt;
 *         &lt;/element&gt;
 *         &lt;element name="seriousness" minOccurs="0"&gt;
 *           &lt;complexType&gt;
 *             &lt;complexContent&gt;
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                 &lt;sequence&gt;
 *                   &lt;element name="serious" minOccurs="0"&gt;
 *                     &lt;simpleType&gt;
 *                       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *                         &lt;enumeration value="Yes"/&gt;
 *                         &lt;enumeration value="No"/&gt;
 *                       &lt;/restriction&gt;
 *                     &lt;/simpleType&gt;
 *                   &lt;/element&gt;
 *                   &lt;element name="congenital_anomaly" minOccurs="0"&gt;
 *                     &lt;simpleType&gt;
 *                       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *                         &lt;enumeration value="Yes"/&gt;
 *                         &lt;enumeration value="No"/&gt;
 *                       &lt;/restriction&gt;
 *                     &lt;/simpleType&gt;
 *                   &lt;/element&gt;
 *                   &lt;element name="death" minOccurs="0"&gt;
 *                     &lt;simpleType&gt;
 *                       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *                         &lt;enumeration value="Yes"/&gt;
 *                         &lt;enumeration value="No"/&gt;
 *                       &lt;/restriction&gt;
 *                     &lt;/simpleType&gt;
 *                   &lt;/element&gt;
 *                   &lt;element name="disability" minOccurs="0"&gt;
 *                     &lt;simpleType&gt;
 *                       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *                         &lt;enumeration value="Yes"/&gt;
 *                         &lt;enumeration value="No"/&gt;
 *                       &lt;/restriction&gt;
 *                     &lt;/simpleType&gt;
 *                   &lt;/element&gt;
 *                   &lt;element name="hospitalized" minOccurs="0"&gt;
 *                     &lt;simpleType&gt;
 *                       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *                         &lt;enumeration value="Yes"/&gt;
 *                         &lt;enumeration value="No"/&gt;
 *                       &lt;/restriction&gt;
 *                     &lt;/simpleType&gt;
 *                   &lt;/element&gt;
 *                   &lt;element name="intervention_required_device" minOccurs="0"&gt;
 *                     &lt;simpleType&gt;
 *                       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *                         &lt;enumeration value="Yes"/&gt;
 *                         &lt;enumeration value="No"/&gt;
 *                       &lt;/restriction&gt;
 *                     &lt;/simpleType&gt;
 *                   &lt;/element&gt;
 *                   &lt;element name="life_threatening" minOccurs="0"&gt;
 *                     &lt;simpleType&gt;
 *                       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *                         &lt;enumeration value="Yes"/&gt;
 *                         &lt;enumeration value="No"/&gt;
 *                       &lt;/restriction&gt;
 *                     &lt;/simpleType&gt;
 *                   &lt;/element&gt;
 *                   &lt;element name="medically_significant" minOccurs="0"&gt;
 *                     &lt;simpleType&gt;
 *                       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *                         &lt;enumeration value="Yes"/&gt;
 *                         &lt;enumeration value="No"/&gt;
 *                       &lt;/restriction&gt;
 *                     &lt;/simpleType&gt;
 *                   &lt;/element&gt;
 *                   &lt;element name="not_reported" minOccurs="0"&gt;
 *                     &lt;simpleType&gt;
 *                       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *                         &lt;enumeration value="Yes"/&gt;
 *                         &lt;enumeration value="No"/&gt;
 *                       &lt;/restriction&gt;
 *                     &lt;/simpleType&gt;
 *                   &lt;/element&gt;
 *                 &lt;/sequence&gt;
 *               &lt;/restriction&gt;
 *             &lt;/complexContent&gt;
 *           &lt;/complexType&gt;
 *         &lt;/element&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
        "transaction",
        "sourceDocuments",
        "sourceSystem",
        "receivedFromLicensePartner",
        "privateData",
        "caseType",
        "countryOfOccurrence",
        "adverseEvents",
        "additionalCaseDetails",
        "products",
        "receiveDate",
        "priority",
        "reporterType",
        "receivingSite",
        "studyId",
        "seriousUnexpectedReaction",
        "seriousness"
})
@XmlRootElement(name = "source_doc_set")
public class SourceDocSet {

    protected Transaction transaction;
    @XmlElement(name = "source_documents", required = true)
    protected SourceDocuments sourceDocuments;
    @XmlElement(name = "source_system")
    protected String sourceSystem;
    @XmlElement(name = "received_from_license_partner")
    protected String receivedFromLicensePartner;
    @XmlElement(name = "private_data", defaultValue = "No")
    protected String privateData;
    @XmlElement(name = "case_type")
    protected String caseType;
    @XmlElement(name = "country_of_occurrence")
    protected String countryOfOccurrence;
    @XmlElement(name = "adverse_events")
    protected AdverseEvents adverseEvents;
    @XmlElement(name = "additional_case_details")
    protected AdditionalCaseDetails additionalCaseDetails;
    protected Products products;
    @XmlElement(name = "receive_date")
    @XmlSchemaType(name = "date")
    protected XMLGregorianCalendar receiveDate;
    protected String priority;
    @XmlElement(name = "reporter_type")
    protected String reporterType;
    @XmlElement(name = "receiving_site")
    protected String receivingSite;
    @XmlElement(name = "study_id")
    protected String studyId;
    @XmlElement(name = "serious_unexpected_reaction", defaultValue = "No")
    protected String seriousUnexpectedReaction;
    protected Seriousness seriousness;

    /**
     * Gets the value of the transaction property.
     *
     * @return possible object is
     * {@link Transaction }
     */
    public Transaction getTransaction() {
        return transaction;
    }

    /**
     * Sets the value of the transaction property.
     *
     * @param value allowed object is
     *              {@link Transaction }
     */
    public void setTransaction(Transaction value) {
        this.transaction = value;
    }

    /**
     * Gets the value of the sourceDocuments property.
     *
     * @return possible object is
     * {@link SourceDocuments }
     */
    public SourceDocuments getSourceDocuments() {
        return sourceDocuments;
    }

    /**
     * Sets the value of the sourceDocuments property.
     *
     * @param value allowed object is
     *              {@link SourceDocuments }
     */
    public void setSourceDocuments(SourceDocuments value) {
        this.sourceDocuments = value;
    }

    /**
     * Gets the value of the sourceSystem property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getSourceSystem() {
        return sourceSystem;
    }

    /**
     * Sets the value of the sourceSystem property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setSourceSystem(String value) {
        this.sourceSystem = value;
    }

    /**
     * Gets the value of the receivedFromLicensePartner property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getReceivedFromLicensePartner() {
        return receivedFromLicensePartner;
    }

    /**
     * Sets the value of the receivedFromLicensePartner property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setReceivedFromLicensePartner(String value) {
        this.receivedFromLicensePartner = value;
    }

    /**
     * Gets the value of the privateData property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getPrivateData() {
        return privateData;
    }

    /**
     * Sets the value of the privateData property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setPrivateData(String value) {
        this.privateData = value;
    }

    /**
     * Gets the value of the caseType property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getCaseType() {
        return caseType;
    }

    /**
     * Sets the value of the caseType property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setCaseType(String value) {
        this.caseType = value;
    }

    /**
     * Gets the value of the countryOfOccurrence property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getCountryOfOccurrence() {
        return countryOfOccurrence;
    }

    /**
     * Sets the value of the countryOfOccurrence property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setCountryOfOccurrence(String value) {
        this.countryOfOccurrence = value;
    }

    /**
     * Gets the value of the adverseEvents property.
     *
     * @return possible object is
     * {@link AdverseEvents }
     */
    public AdverseEvents getAdverseEvents() {
        return adverseEvents;
    }

    /**
     * Sets the value of the adverseEvents property.
     *
     * @param value allowed object is
     *              {@link AdverseEvents }
     */
    public void setAdverseEvents(AdverseEvents value) {
        this.adverseEvents = value;
    }

    /**
     * Gets the value of the additionalCaseDetails property.
     *
     * @return possible object is
     * {@link AdditionalCaseDetails }
     */
    public AdditionalCaseDetails getAdditionalCaseDetails() {
        return additionalCaseDetails;
    }

    /**
     * Sets the value of the additionalCaseDetails property.
     *
     * @param value allowed object is
     *              {@link AdditionalCaseDetails }
     */
    public void setAdditionalCaseDetails(AdditionalCaseDetails value) {
        this.additionalCaseDetails = value;
    }

    /**
     * Gets the value of the products property.
     *
     * @return possible object is
     * {@link Products }
     */
    public Products getProducts() {
        return products;
    }

    /**
     * Sets the value of the products property.
     *
     * @param value allowed object is
     *              {@link Products }
     */
    public void setProducts(Products value) {
        this.products = value;
    }

    /**
     * Gets the value of the receiveDate property.
     *
     * @return possible object is
     * {@link XMLGregorianCalendar }
     */
    public XMLGregorianCalendar getReceiveDate() {
        return receiveDate;
    }

    /**
     * Sets the value of the receiveDate property.
     *
     * @param value allowed object is
     *              {@link XMLGregorianCalendar }
     */
    public void setReceiveDate(XMLGregorianCalendar value) {
        this.receiveDate = value;
    }

    /**
     * Gets the value of the priority property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getPriority() {
        return priority;
    }

    /**
     * Sets the value of the priority property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setPriority(String value) {
        this.priority = value;
    }

    /**
     * Gets the value of the reporterType property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getReporterType() {
        return reporterType;
    }

    /**
     * Sets the value of the reporterType property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setReporterType(String value) {
        this.reporterType = value;
    }

    /**
     * Gets the value of the receivingSite property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getReceivingSite() {
        return receivingSite;
    }

    /**
     * Sets the value of the receivingSite property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setReceivingSite(String value) {
        this.receivingSite = value;
    }

    /**
     * Gets the value of the studyId property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getStudyId() {
        return studyId;
    }

    /**
     * Sets the value of the studyId property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setStudyId(String value) {
        this.studyId = value;
    }

    /**
     * Gets the value of the seriousUnexpectedReaction property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getSeriousUnexpectedReaction() {
        return seriousUnexpectedReaction;
    }

    /**
     * Sets the value of the seriousUnexpectedReaction property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setSeriousUnexpectedReaction(String value) {
        this.seriousUnexpectedReaction = value;
    }

    /**
     * Gets the value of the seriousness property.
     *
     * @return possible object is
     * {@link Seriousness }
     */
    public Seriousness getSeriousness() {
        return seriousness;
    }

    /**
     * Sets the value of the seriousness property.
     *
     * @param value allowed object is
     *              {@link Seriousness }
     */
    public void setSeriousness(Seriousness value) {
        this.seriousness = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     *
     * <p>The following schema fragment specifies the expected content contained within this class.
     *
     * <pre>
     * &lt;complexType&gt;
     *   &lt;complexContent&gt;
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
     *       &lt;sequence&gt;
     *         &lt;element name="additional_case_detail" maxOccurs="unbounded"&gt;
     *           &lt;complexType&gt;
     *             &lt;complexContent&gt;
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
     *                 &lt;sequence&gt;
     *                   &lt;element name="additional_data_description" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
     *                   &lt;element name="additional_data_value" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
     *                 &lt;/sequence&gt;
     *               &lt;/restriction&gt;
     *             &lt;/complexContent&gt;
     *           &lt;/complexType&gt;
     *         &lt;/element&gt;
     *       &lt;/sequence&gt;
     *     &lt;/restriction&gt;
     *   &lt;/complexContent&gt;
     * &lt;/complexType&gt;
     * </pre>
     */
    @XmlRootElement(name = "source_doc_set")
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
            "additionalCaseDetail"
    })
    public static class AdditionalCaseDetails {

        @XmlElement(name = "additional_case_detail", required = true)
        protected List<AdditionalCaseDetail> additionalCaseDetail;

        /**
         * Gets the value of the additionalCaseDetail property.
         *
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the additionalCaseDetail property.
         *
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getAdditionalCaseDetail().add(newItem);
         * </pre>
         *
         *
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link AdditionalCaseDetail }
         */
        public List<AdditionalCaseDetail> getAdditionalCaseDetail() {
            if (additionalCaseDetail == null) {
                additionalCaseDetail = new ArrayList<AdditionalCaseDetail>();
            }
            return this.additionalCaseDetail;
        }


        /**
         * <p>Java class for anonymous complex type.
         *
         * <p>The following schema fragment specifies the expected content contained within this class.
         *
         * <pre>
         * &lt;complexType&gt;
         *   &lt;complexContent&gt;
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
         *       &lt;sequence&gt;
         *         &lt;element name="additional_data_description" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
         *         &lt;element name="additional_data_value" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
         *       &lt;/sequence&gt;
         *     &lt;/restriction&gt;
         *   &lt;/complexContent&gt;
         * &lt;/complexType&gt;
         * </pre>
         */
        @XmlRootElement(name = "additional_case_details")
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
                "additionalDataDescription",
                "additionalDataValue"
        })
        public static class AdditionalCaseDetail {

            @XmlElement(name = "additional_data_description", required = true)
            protected String additionalDataDescription;
            @XmlElement(name = "additional_data_value", required = true)
            protected String additionalDataValue;

            /**
             * Gets the value of the additionalDataDescription property.
             *
             * @return possible object is
             * {@link String }
             */
            public String getAdditionalDataDescription() {
                return additionalDataDescription;
            }

            /**
             * Sets the value of the additionalDataDescription property.
             *
             * @param value allowed object is
             *              {@link String }
             */
            public void setAdditionalDataDescription(String value) {
                this.additionalDataDescription = value;
            }

            /**
             * Gets the value of the additionalDataValue property.
             *
             * @return possible object is
             * {@link String }
             */
            public String getAdditionalDataValue() {
                return additionalDataValue;
            }

            /**
             * Sets the value of the additionalDataValue property.
             *
             * @param value allowed object is
             *              {@link String }
             */
            public void setAdditionalDataValue(String value) {
                this.additionalDataValue = value;
            }

        }

    }


    /**
     * <p>Java class for anonymous complex type.
     *
     * <p>The following schema fragment specifies the expected content contained within this class.
     *
     * <pre>
     * &lt;complexType&gt;
     *   &lt;complexContent&gt;
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
     *       &lt;sequence&gt;
     *         &lt;element name="adverse_event" maxOccurs="unbounded"&gt;
     *           &lt;complexType&gt;
     *             &lt;complexContent&gt;
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
     *                 &lt;sequence&gt;
     *                   &lt;element name="event_verbatim" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
     *                   &lt;element name="event_code" type="{http://www.w3.org/2001/XMLSchema}nonNegativeInteger" minOccurs="0"/&gt;
     *                   &lt;element name="event_code_type" minOccurs="0"&gt;
     *                     &lt;simpleType&gt;
     *                       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
     *                         &lt;enumeration value="PT"/&gt;
     *                         &lt;enumeration value="LLT"/&gt;
     *                       &lt;/restriction&gt;
     *                     &lt;/simpleType&gt;
     *                   &lt;/element&gt;
     *                 &lt;/sequence&gt;
     *               &lt;/restriction&gt;
     *             &lt;/complexContent&gt;
     *           &lt;/complexType&gt;
     *         &lt;/element&gt;
     *       &lt;/sequence&gt;
     *     &lt;/restriction&gt;
     *   &lt;/complexContent&gt;
     * &lt;/complexType&gt;
     * </pre>
     */
    @XmlRootElement(name = "adverse_events")
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
            "adverseEvent"
    })
    public static class AdverseEvents {

        @XmlElement(name = "adverse_event", required = true)
        protected List<AdverseEvent> adverseEvent;

        /**
         * Gets the value of the adverseEvent property.
         *
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the adverseEvent property.
         *
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getAdverseEvent().add(newItem);
         * </pre>
         *
         *
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link AdverseEvent }
         */
        public List<AdverseEvent> getAdverseEvent() {
            if (adverseEvent == null) {
                adverseEvent = new ArrayList<AdverseEvent>();
            }
            return this.adverseEvent;
        }


        /**
         * <p>Java class for anonymous complex type.
         *
         * <p>The following schema fragment specifies the expected content contained within this class.
         *
         * <pre>
         * &lt;complexType&gt;
         *   &lt;complexContent&gt;
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
         *       &lt;sequence&gt;
         *         &lt;element name="event_verbatim" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
         *         &lt;element name="event_code" type="{http://www.w3.org/2001/XMLSchema}nonNegativeInteger" minOccurs="0"/&gt;
         *         &lt;element name="event_code_type" minOccurs="0"&gt;
         *           &lt;simpleType&gt;
         *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
         *               &lt;enumeration value="PT"/&gt;
         *               &lt;enumeration value="LLT"/&gt;
         *             &lt;/restriction&gt;
         *           &lt;/simpleType&gt;
         *         &lt;/element&gt;
         *       &lt;/sequence&gt;
         *     &lt;/restriction&gt;
         *   &lt;/complexContent&gt;
         * &lt;/complexType&gt;
         * </pre>
         */
        @XmlRootElement(name = "adverse_events")
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
                "eventVerbatim",
                "eventCode",
                "eventCodeType"
        })
        public static class AdverseEvent {

            @XmlElement(name = "event_verbatim", required = true)
            protected String eventVerbatim;
            @XmlElement(name = "event_code")
            @XmlSchemaType(name = "nonNegativeInteger")
            protected BigInteger eventCode;
            @XmlElement(name = "event_code_type", defaultValue = "LLT")
            protected String eventCodeType;

            /**
             * Gets the value of the eventVerbatim property.
             *
             * @return possible object is
             * {@link String }
             */
            public String getEventVerbatim() {
                return eventVerbatim;
            }

            /**
             * Sets the value of the eventVerbatim property.
             *
             * @param value allowed object is
             *              {@link String }
             */
            public void setEventVerbatim(String value) {
                this.eventVerbatim = value;
            }

            /**
             * Gets the value of the eventCode property.
             *
             * @return possible object is
             * {@link BigInteger }
             */
            public BigInteger getEventCode() {
                return eventCode;
            }

            /**
             * Sets the value of the eventCode property.
             *
             * @param value allowed object is
             *              {@link BigInteger }
             */
            public void setEventCode(BigInteger value) {
                this.eventCode = value;
            }

            /**
             * Gets the value of the eventCodeType property.
             *
             * @return possible object is
             * {@link String }
             */
            public String getEventCodeType() {
                return eventCodeType;
            }

            /**
             * Sets the value of the eventCodeType property.
             *
             * @param value allowed object is
             *              {@link String }
             */
            public void setEventCodeType(String value) {
                this.eventCodeType = value;
            }

        }

    }


    /**
     * <p>Java class for anonymous complex type.
     *
     * <p>The following schema fragment specifies the expected content contained within this class.
     *
     * <pre>
     * &lt;complexType&gt;
     *   &lt;complexContent&gt;
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
     *       &lt;sequence&gt;
     *         &lt;element name="product" maxOccurs="unbounded"&gt;
     *           &lt;complexType&gt;
     *             &lt;complexContent&gt;
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
     *                 &lt;sequence&gt;
     *                   &lt;element name="product_name" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
     *                   &lt;element name="generic_name" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
     *                 &lt;/sequence&gt;
     *               &lt;/restriction&gt;
     *             &lt;/complexContent&gt;
     *           &lt;/complexType&gt;
     *         &lt;/element&gt;
     *       &lt;/sequence&gt;
     *     &lt;/restriction&gt;
     *   &lt;/complexContent&gt;
     * &lt;/complexType&gt;
     * </pre>
     */
    @XmlRootElement(name = "products")
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
            "product"
    })
    public static class Products {

        @XmlElement(required = true)
        protected List<Product> product;

        /**
         * Gets the value of the product property.
         *
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the product property.
         *
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getProduct().add(newItem);
         * </pre>
         *
         *
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link Product }
         */
        public List<Product> getProduct() {
            if (product == null) {
                product = new ArrayList<Product>();
            }
            return this.product;
        }


        /**
         * <p>Java class for anonymous complex type.
         *
         * <p>The following schema fragment specifies the expected content contained within this class.
         *
         * <pre>
         * &lt;complexType&gt;
         *   &lt;complexContent&gt;
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
         *       &lt;sequence&gt;
         *         &lt;element name="product_name" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
         *         &lt;element name="generic_name" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
         *       &lt;/sequence&gt;
         *     &lt;/restriction&gt;
         *   &lt;/complexContent&gt;
         * &lt;/complexType&gt;
         * </pre>
         */
        @XmlRootElement(name = "product")
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
                "productName",
                "genericName"
        })
        public static class Product {

            @XmlElement(name = "product_name", required = true)
            protected String productName;
            @XmlElement(name = "generic_name")
            protected String genericName;

            /**
             * Gets the value of the productName property.
             *
             * @return possible object is
             * {@link String }
             */
            public String getProductName() {
                return productName;
            }

            /**
             * Sets the value of the productName property.
             *
             * @param value allowed object is
             *              {@link String }
             */
            public void setProductName(String value) {
                this.productName = value;
            }

            /**
             * Gets the value of the genericName property.
             *
             * @return possible object is
             * {@link String }
             */
            public String getGenericName() {
                return genericName;
            }

            /**
             * Sets the value of the genericName property.
             *
             * @param value allowed object is
             *              {@link String }
             */
            public void setGenericName(String value) {
                this.genericName = value;
            }

        }

    }


    /**
     * <p>Java class for anonymous complex type.
     *
     * <p>The following schema fragment specifies the expected content contained within this class.
     *
     * <pre>
     * &lt;complexType&gt;
     *   &lt;complexContent&gt;
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
     *       &lt;sequence&gt;
     *         &lt;element name="serious" minOccurs="0"&gt;
     *           &lt;simpleType&gt;
     *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
     *               &lt;enumeration value="Yes"/&gt;
     *               &lt;enumeration value="No"/&gt;
     *             &lt;/restriction&gt;
     *           &lt;/simpleType&gt;
     *         &lt;/element&gt;
     *         &lt;element name="congenital_anomaly" minOccurs="0"&gt;
     *           &lt;simpleType&gt;
     *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
     *               &lt;enumeration value="Yes"/&gt;
     *               &lt;enumeration value="No"/&gt;
     *             &lt;/restriction&gt;
     *           &lt;/simpleType&gt;
     *         &lt;/element&gt;
     *         &lt;element name="death" minOccurs="0"&gt;
     *           &lt;simpleType&gt;
     *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
     *               &lt;enumeration value="Yes"/&gt;
     *               &lt;enumeration value="No"/&gt;
     *             &lt;/restriction&gt;
     *           &lt;/simpleType&gt;
     *         &lt;/element&gt;
     *         &lt;element name="disability" minOccurs="0"&gt;
     *           &lt;simpleType&gt;
     *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
     *               &lt;enumeration value="Yes"/&gt;
     *               &lt;enumeration value="No"/&gt;
     *             &lt;/restriction&gt;
     *           &lt;/simpleType&gt;
     *         &lt;/element&gt;
     *         &lt;element name="hospitalized" minOccurs="0"&gt;
     *           &lt;simpleType&gt;
     *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
     *               &lt;enumeration value="Yes"/&gt;
     *               &lt;enumeration value="No"/&gt;
     *             &lt;/restriction&gt;
     *           &lt;/simpleType&gt;
     *         &lt;/element&gt;
     *         &lt;element name="intervention_required_device" minOccurs="0"&gt;
     *           &lt;simpleType&gt;
     *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
     *               &lt;enumeration value="Yes"/&gt;
     *               &lt;enumeration value="No"/&gt;
     *             &lt;/restriction&gt;
     *           &lt;/simpleType&gt;
     *         &lt;/element&gt;
     *         &lt;element name="life_threatening" minOccurs="0"&gt;
     *           &lt;simpleType&gt;
     *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
     *               &lt;enumeration value="Yes"/&gt;
     *               &lt;enumeration value="No"/&gt;
     *             &lt;/restriction&gt;
     *           &lt;/simpleType&gt;
     *         &lt;/element&gt;
     *         &lt;element name="medically_significant" minOccurs="0"&gt;
     *           &lt;simpleType&gt;
     *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
     *               &lt;enumeration value="Yes"/&gt;
     *               &lt;enumeration value="No"/&gt;
     *             &lt;/restriction&gt;
     *           &lt;/simpleType&gt;
     *         &lt;/element&gt;
     *         &lt;element name="not_reported" minOccurs="0"&gt;
     *           &lt;simpleType&gt;
     *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
     *               &lt;enumeration value="Yes"/&gt;
     *               &lt;enumeration value="No"/&gt;
     *             &lt;/restriction&gt;
     *           &lt;/simpleType&gt;
     *         &lt;/element&gt;
     *       &lt;/sequence&gt;
     *     &lt;/restriction&gt;
     *   &lt;/complexContent&gt;
     * &lt;/complexType&gt;
     * </pre>
     */
    @XmlRootElement(name = "seriousness")
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
            "serious",
            "congenitalAnomaly",
            "death",
            "disability",
            "hospitalized",
            "interventionRequiredDevice",
            "lifeThreatening",
            "medicallySignificant",
            "notReported"
    })
    public static class Seriousness {

        protected String serious;
        @XmlElement(name = "congenital_anomaly")
        protected String congenitalAnomaly;
        protected String death;
        protected String disability;
        protected String hospitalized;
        @XmlElement(name = "intervention_required_device")
        protected String interventionRequiredDevice;
        @XmlElement(name = "life_threatening")
        protected String lifeThreatening;
        @XmlElement(name = "medically_significant")
        protected String medicallySignificant;
        @XmlElement(name = "not_reported")
        protected String notReported;

        /**
         * Gets the value of the serious property.
         *
         * @return possible object is
         * {@link String }
         */
        public String getSerious() {
            return serious;
        }

        /**
         * Sets the value of the serious property.
         *
         * @param value allowed object is
         *              {@link String }
         */
        public void setSerious(String value) {
            this.serious = value;
        }

        /**
         * Gets the value of the congenitalAnomaly property.
         *
         * @return possible object is
         * {@link String }
         */
        public String getCongenitalAnomaly() {
            return congenitalAnomaly;
        }

        /**
         * Sets the value of the congenitalAnomaly property.
         *
         * @param value allowed object is
         *              {@link String }
         */
        public void setCongenitalAnomaly(String value) {
            this.congenitalAnomaly = value;
        }

        /**
         * Gets the value of the death property.
         *
         * @return possible object is
         * {@link String }
         */
        public String getDeath() {
            return death;
        }

        /**
         * Sets the value of the death property.
         *
         * @param value allowed object is
         *              {@link String }
         */
        public void setDeath(String value) {
            this.death = value;
        }

        /**
         * Gets the value of the disability property.
         *
         * @return possible object is
         * {@link String }
         */
        public String getDisability() {
            return disability;
        }

        /**
         * Sets the value of the disability property.
         *
         * @param value allowed object is
         *              {@link String }
         */
        public void setDisability(String value) {
            this.disability = value;
        }

        /**
         * Gets the value of the hospitalized property.
         *
         * @return possible object is
         * {@link String }
         */
        public String getHospitalized() {
            return hospitalized;
        }

        /**
         * Sets the value of the hospitalized property.
         *
         * @param value allowed object is
         *              {@link String }
         */
        public void setHospitalized(String value) {
            this.hospitalized = value;
        }

        /**
         * Gets the value of the interventionRequiredDevice property.
         *
         * @return possible object is
         * {@link String }
         */
        public String getInterventionRequiredDevice() {
            return interventionRequiredDevice;
        }

        /**
         * Sets the value of the interventionRequiredDevice property.
         *
         * @param value allowed object is
         *              {@link String }
         */
        public void setInterventionRequiredDevice(String value) {
            this.interventionRequiredDevice = value;
        }

        /**
         * Gets the value of the lifeThreatening property.
         *
         * @return possible object is
         * {@link String }
         */
        public String getLifeThreatening() {
            return lifeThreatening;
        }

        /**
         * Sets the value of the lifeThreatening property.
         *
         * @param value allowed object is
         *              {@link String }
         */
        public void setLifeThreatening(String value) {
            this.lifeThreatening = value;
        }

        /**
         * Gets the value of the medicallySignificant property.
         *
         * @return possible object is
         * {@link String }
         */
        public String getMedicallySignificant() {
            return medicallySignificant;
        }

        /**
         * Sets the value of the medicallySignificant property.
         *
         * @param value allowed object is
         *              {@link String }
         */
        public void setMedicallySignificant(String value) {
            this.medicallySignificant = value;
        }

        /**
         * Gets the value of the notReported property.
         *
         * @return possible object is
         * {@link String }
         */
        public String getNotReported() {
            return notReported;
        }

        /**
         * Sets the value of the notReported property.
         *
         * @param value allowed object is
         *              {@link String }
         */
        public void setNotReported(String value) {
            this.notReported = value;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     *
     * <p>The following schema fragment specifies the expected content contained within this class.
     *
     * <pre>
     * &lt;complexType&gt;
     *   &lt;complexContent&gt;
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
     *       &lt;sequence&gt;
     *         &lt;element name="source_document" maxOccurs="unbounded"&gt;
     *           &lt;complexType&gt;
     *             &lt;complexContent&gt;
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
     *                 &lt;sequence&gt;
     *                   &lt;element name="document_name"&gt;
     *                     &lt;simpleType&gt;
     *                       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
     *                         &lt;minLength value="1"/&gt;
     *                       &lt;/restriction&gt;
     *                     &lt;/simpleType&gt;
     *                   &lt;/element&gt;
     *                   &lt;element name="edms_doc_object_id"&gt;
     *                     &lt;simpleType&gt;
     *                       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
     *                         &lt;minLength value="1"/&gt;
     *                       &lt;/restriction&gt;
     *                     &lt;/simpleType&gt;
     *                   &lt;/element&gt;
     *                   &lt;element name="process_document" type="{http://www.w3.org/2001/XMLSchema}boolean"/&gt;
     *                   &lt;element name="document_language"&gt;
     *                     &lt;simpleType&gt;
     *                       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
     *                         &lt;minLength value="2"/&gt;
     *                         &lt;maxLength value="2"/&gt;
     *                       &lt;/restriction&gt;
     *                     &lt;/simpleType&gt;
     *                   &lt;/element&gt;
     *                   &lt;element name="document_uri" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
     *                 &lt;/sequence&gt;
     *               &lt;/restriction&gt;
     *             &lt;/complexContent&gt;
     *           &lt;/complexType&gt;
     *         &lt;/element&gt;
     *       &lt;/sequence&gt;
     *     &lt;/restriction&gt;
     *   &lt;/complexContent&gt;
     * &lt;/complexType&gt;
     * </pre>
     */
    @XmlRootElement(name = "source_documents")
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
            "sourceDocument"
    })
    public static class SourceDocuments {

        @XmlElement(name = "source_document", required = true)
        protected List<SourceDocument> sourceDocument;

        /**
         * Gets the value of the sourceDocument property.
         *
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the sourceDocument property.
         *
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getSourceDocument().add(newItem);
         * </pre>
         *
         *
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link SourceDocument }
         */
        public List<SourceDocument> getSourceDocument() {
            if (sourceDocument == null) {
                sourceDocument = new ArrayList<SourceDocument>();
            }
            return this.sourceDocument;
        }


        /**
         * <p>Java class for anonymous complex type.
         *
         * <p>The following schema fragment specifies the expected content contained within this class.
         *
         * <pre>
         * &lt;complexType&gt;
         *   &lt;complexContent&gt;
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
         *       &lt;sequence&gt;
         *         &lt;element name="document_name"&gt;
         *           &lt;simpleType&gt;
         *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
         *               &lt;minLength value="1"/&gt;
         *             &lt;/restriction&gt;
         *           &lt;/simpleType&gt;
         *         &lt;/element&gt;
         *         &lt;element name="edms_doc_object_id"&gt;
         *           &lt;simpleType&gt;
         *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
         *               &lt;minLength value="1"/&gt;
         *             &lt;/restriction&gt;
         *           &lt;/simpleType&gt;
         *         &lt;/element&gt;
         *         &lt;element name="process_document" type="{http://www.w3.org/2001/XMLSchema}boolean"/&gt;
         *         &lt;element name="document_language"&gt;
         *           &lt;simpleType&gt;
         *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
         *               &lt;minLength value="2"/&gt;
         *               &lt;maxLength value="2"/&gt;
         *             &lt;/restriction&gt;
         *           &lt;/simpleType&gt;
         *         &lt;/element&gt;
         *         &lt;element name="document_uri" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
         *       &lt;/sequence&gt;
         *     &lt;/restriction&gt;
         *   &lt;/complexContent&gt;
         * &lt;/complexType&gt;
         * </pre>
         */
        @XmlRootElement(name = "source_document")
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
                "documentName",
                "edmsDocObjectId",
                "processDocument",
                "documentLanguage",
                "documentUri"
        })
        public static class SourceDocument {

            @XmlElement(name = "document_name", required = true)
            protected String documentName;
            @XmlElement(name = "edms_doc_object_id", required = true)
            protected String edmsDocObjectId;
            @XmlElement(name = "process_document", defaultValue = "0")
            protected boolean processDocument;
            @XmlElement(name = "document_language", required = true)
            protected String documentLanguage;
            @XmlElement(name = "document_uri")
            protected String documentUri;

            /**
             * Gets the value of the documentName property.
             *
             * @return possible object is
             * {@link String }
             */
            public String getDocumentName() {
                return documentName;
            }

            /**
             * Sets the value of the documentName property.
             *
             * @param value allowed object is
             *              {@link String }
             */
            public void setDocumentName(String value) {
                this.documentName = value;
            }

            /**
             * Gets the value of the edmsDocObjectId property.
             *
             * @return possible object is
             * {@link String }
             */
            public String getEdmsDocObjectId() {
                return edmsDocObjectId;
            }

            /**
             * Sets the value of the edmsDocObjectId property.
             *
             * @param value allowed object is
             *              {@link String }
             */
            public void setEdmsDocObjectId(String value) {
                this.edmsDocObjectId = value;
            }

            /**
             * Gets the value of the processDocument property.
             */
            public boolean isProcessDocument() {
                return processDocument;
            }

            /**
             * Sets the value of the processDocument property.
             */
            public void setProcessDocument(boolean value) {
                this.processDocument = value;
            }

            /**
             * Gets the value of the documentLanguage property.
             *
             * @return possible object is
             * {@link String }
             */
            public String getDocumentLanguage() {
                return documentLanguage;
            }

            /**
             * Sets the value of the documentLanguage property.
             *
             * @param value allowed object is
             *              {@link String }
             */
            public void setDocumentLanguage(String value) {
                this.documentLanguage = value;
            }

            /**
             * Gets the value of the documentUri property.
             *
             * @return possible object is
             * {@link String }
             */
            public String getDocumentUri() {
                return documentUri;
            }

            /**
             * Sets the value of the documentUri property.
             *
             * @param value allowed object is
             *              {@link String }
             */
            public void setDocumentUri(String value) {
                this.documentUri = value;
            }

        }

    }


    /**
     * <p>Java class for anonymous complex type.
     *
     * <p>The following schema fragment specifies the expected content contained within this class.
     *
     * <pre>
     * &lt;complexType&gt;
     *   &lt;complexContent&gt;
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
     *       &lt;sequence&gt;
     *         &lt;element name="transaction_number" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
     *         &lt;element name="transaction_date" type="{http://www.w3.org/2001/XMLSchema}dateTime" minOccurs="0"/&gt;
     *       &lt;/sequence&gt;
     *     &lt;/restriction&gt;
     *   &lt;/complexContent&gt;
     * &lt;/complexType&gt;
     * </pre>
     */
    @XmlRootElement(name = "transaction")
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
            "transactionNumber",
            "transactionDate"
    })
    public static class Transaction {

        @XmlElement(name = "transaction_number", required = true)
        protected String transactionNumber;
        @XmlElement(name = "transaction_date")
        @XmlSchemaType(name = "dateTime")
        protected XMLGregorianCalendar transactionDate;

        /**
         * Gets the value of the transactionNumber property.
         *
         * @return possible object is
         * {@link String }
         */
        public String getTransactionNumber() {
            return transactionNumber;
        }

        /**
         * Sets the value of the transactionNumber property.
         *
         * @param value allowed object is
         *              {@link String }
         */
        public void setTransactionNumber(String value) {
            this.transactionNumber = value;
        }

        /**
         * Gets the value of the transactionDate property.
         *
         * @return possible object is
         * {@link XMLGregorianCalendar }
         */
        public XMLGregorianCalendar getTransactionDate() {
            return transactionDate;
        }

        /**
         * Sets the value of the transactionDate property.
         *
         * @param value allowed object is
         *              {@link XMLGregorianCalendar }
         */
        public void setTransactionDate(XMLGregorianCalendar value) {
            this.transactionDate = value;
        }

    }

}
